# List of the blocked words, seperated with a comma, example: word1,word2,word3
badwords: fuck,shit,motherfucker,bitch,asshole,
# Message that is shown to the player when his message has been blocked
blockmessage: §eYour message has been §cblocked §eby LEET-BLOCK.
